version: '3'
services:
  app:
    build:
      context: ./backend
    container_name: fastapi-phresh-app
    volumes:
      - ./backend/:/backend/
    command: python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.api.server:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
      - 5678:5678
    env_file:
      - ./backend/.env
    depends_on: 
      - db

  db:
    image: postgres
    container_name: fastapi-phresh-db
    environment:
      - POSTGRES_DB=fastapi-phresh
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=awesome_password
    volumes:
      - fastapi-volume:/var/lib/postgresql/data

volumes:
  fastapi-volume:
    external: true
